language: node_js
node_js: 
  - 13.1.0
script:
  - "npm run build"
  - "npm run test:nowatch"

before_deploy:
  - rvm requirements
  - rvm install 2.6
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
  
deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "book-store-web99"
  on:
    branch: main

