language: node_js
node_js: 
  - 14
script:
  - npm install || (cat /home/travis/.npm/_logs/*.log && false)
  - npm run build
  - npm run test:nowatch

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "book-store-web99"
  on:
    branch: main

